version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: zhadaev
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task-management
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: task-management
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task-management
      SPRING_DATASOURCE_USERNAME: zhadaev
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db